import subprocess

from auditlib import plan


def test_vendor_and_lockfiles_excluded():
    assert plan.is_excluded("src/css/vendor/font-awesome.css")
    assert plan.is_excluded("package-lock.json")
    assert plan.is_excluded("web/app.min.js")
    assert not plan.is_excluded("src/js/app.js")


def test_generated_marker():
    assert plan.is_generated("// Code generated by protoc. DO NOT EDIT.")
    assert not plan.is_generated("function main() {}")


def test_extra_globs_exclude():
    assert plan.is_excluded("docs/api.html", ["docs/*"])


def test_shard_key():
    assert plan.shard_key("README.md") == "."
    assert plan.shard_key("src/js/a.js") == "src/js"
    assert plan.shard_key("gulp.d/tasks/a.js") == "gulp.d"
    assert plan.shard_key("src/a.js") == "src"


def test_churn_parse():
    log = "src/a.js\nsrc/b.js\n\nsrc/a.js\n"
    assert dict(plan.parse_churn(log)) == {"src/a.js": 2, "src/b.js": 1}


def test_ranking_prefers_churn_times_size():
    files = [("hot/a.js", 100_000), ("cold/b.js", 100_000), ("big/c.js", 400_000)]
    ranked = plan.build_plan(files, {"hot/a.js": 30, "cold/b.js": 1}, small_repo_bytes=1)
    assert [u["unit"] for u in ranked] == ["hot", "big", "cold"]


def test_small_repo_is_single_shard():
    files = [("a/x.js", 100), ("b/y.js", 100)]
    units = plan.build_plan(files, {}, small_repo_bytes=10_000)
    assert [u["unit"] for u in units] == ["."]
    assert len(units[0]["files"]) == 2


def test_empty_input_yields_no_units():
    assert plan.build_plan([], {}) == []


def test_oversize_directory_splits_without_splitting_files():
    files = [(f"big/f{i}.js", 400_000) for i in range(5)]
    units = plan.build_plan(files, {}, small_repo_bytes=1, cap_tokens=250_000)
    assert [u["unit"] for u in units] == ["big", "big#2", "big#3"]
    assert sum(len(u["files"]) for u in units) == 5


def test_single_oversize_file_gets_its_own_unit():
    units = plan.build_plan([("a/huge.js", 4_000_000)], {}, small_repo_bytes=1, cap_tokens=1000)
    assert units[0]["files"] == ["a/huge.js"] and units[0]["oversize"] is True


def test_est_cost_applies_multiplier():
    unit = plan.build_plan([("a/x.js", 4000)], {}, small_repo_bytes=1)[0]
    assert unit["est_tokens"] == 1000
    assert unit["est_cost"] == 1000 * plan.ANALYSIS_MULTIPLIER


def test_tracked_files_handles_spaces(tmp_path):
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    (tmp_path / "a b.js").write_text("x")
    subprocess.run(["git", "-C", str(tmp_path), "add", "."], check=True)
    assert plan.tracked_files(tmp_path) == [("a b.js", 1)]


def test_churn_on_repo_without_commits_is_empty(tmp_path):
    subprocess.run(["git", "init", "-q", str(tmp_path)], check=True)
    assert dict(plan.churn(tmp_path)) == {}


def test_binary_assets_are_excluded_by_suffix():
    for name in ("src/font/a.woff2", "src/font/a.otf", "img/logo.png", "lib/app.jar", "doc/spec.pdf"):
        assert plan.is_excluded(name), name


def test_nul_bytes_mark_content_as_binary():
    assert plan.is_binary(b"abc\x00def")
    assert not plan.is_binary("héllo".encode())


def test_changed_since_and_churn_are_relative_to_a_subdirectory(tmp_path):
    def git(*args):
        subprocess.run(["git", "-C", str(tmp_path), "-c", "user.name=t", "-c", "user.email=t@t", *args],
                       check=True, capture_output=True)

    git("init", "-q")
    (tmp_path / "sub").mkdir()
    (tmp_path / "sub" / "a.js").write_text("1")
    git("add", ".")
    git("commit", "-qm", "one")
    (tmp_path / "sub" / "a.js").write_text("2")
    git("commit", "-qam", "two")
    assert plan.changed_since(tmp_path / "sub", "HEAD~1") == ["a.js"]
    assert plan.churn(tmp_path / "sub")["a.js"] >= 1


def test_parse_churn_accepts_nul_separated_logs():
    assert dict(plan.parse_churn("a.js\0b.js\0\0a.js\0")) == {"a.js": 2, "b.js": 1}


def test_churn_counts_paths_git_would_quote(tmp_path):
    def git(*args):
        subprocess.run(["git", "-C", str(tmp_path), "-c", "user.name=t", "-c", "user.email=t@t", *args],
                       check=True, capture_output=True)

    git("init", "-q")
    (tmp_path / 'we"ird.js').write_text("1")
    git("add", ".")
    git("commit", "-qm", "one")
    assert plan.churn(tmp_path)['we"ird.js'] >= 1
